name: Build HDF5

on:
  push:
    branches:
      - master
    paths:
      - h5py/build.sh
      - h5py/VERSION
      - trigger.sh
      - .github/workflows/h5py.yaml
      - .github/workflows/build.yaml
  
jobs:
  build_h5py:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Trigger build
        run: bash trigger.sh
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          NAME: h5py
          DISPLAY_NAME: HDF5 for Python
